# Use an official Python runtime as a parent image
FROM python:3.12-slim-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

# Install Poetry
RUN pip install poetry==2.1.1 

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Copy the pyproject.toml and poetry.lock files to the container
COPY pyproject.toml poetry.lock ./

# Install the dependencies
RUN poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi



#TODO Improve this 
WORKDIR /app/app

#TODO change to multi-stage build

# Create a non-root user
# RUN useradd -m appuser
# USER appuser

EXPOSE 80


CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--workers", "4"]

